name: Helm Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Minikube
      uses: medyagh/setup-minikube@latest

    - name: Create namespace if not exists
      run: |
        kubectl get ns grafana-nyoba || kubectl create ns grafana-nyoba

    - name: Helm upgrade/install
      run: |
        helm upgrade --install my-grafana ./helm-chart -n grafana-nyoba --wait
