name: Deploy Nyoba (Grafana) to Minikube

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Helm
      uses: azure/setup-helm@v3

    - name: Setup Minikube
      uses: medyagh/setup-minikube@latest
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy Helm Chart
      run: |
        helm install nyoba ./helm-chart --wait
        kubectl get svc
