name: Test Grafana API

on:
  workflow_dispatch:

jobs:
  grafana-check:
    runs-on: self-hosted

    steps:
      - name: Cek koneksi ke Grafana
        run: |
          echo "Cek koneksi ke Grafana di http://localhost:3000"
          curl -I http://localhost:3000

      - name: Cek login admin
        env:
          GRAFANA_USER: admin
          GRAFANA_PASS: ${{ secrets.GRAFANA_PASS }}
        run: |
          echo "Cek login menggunakan API"
          curl -s -u $GRAFANA_USER:$GRAFANA_PASS http://localhost:3000/api/org | jq
